name: dc-healthcare

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - osfclient
  - git
  - git-annex
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - shap
